<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="4" hostname="LAPTOP-VO3PD6LI" name="com.deltaX.QATCs.RegisterationFormDataDrivenTestNG" tests="7" failures="1" timestamp="03 Jul 2018 19:57:47 GMT" time="22.450" errors="0">
  <testcase name="RegisterationWithDataDriven" time="6.714" classname="com.deltaX.QATCs.RegisterationFormDataDrivenTestNG">
    <skipped/>
  </testcase> <!-- RegisterationWithDataDriven -->
  <testcase name="RegisterationWithDataDriven" time="7.191" classname="com.deltaX.QATCs.RegisterationFormDataDrivenTestNG">
    <skipped/>
  </testcase> <!-- RegisterationWithDataDriven -->
  <testcase name="RegisterationWithDataDriven" time="0.752" classname="com.deltaX.QATCs.RegisterationFormDataDrivenTestNG">
    <skipped/>
  </testcase> <!-- RegisterationWithDataDriven -->
  <testcase name="RegisterationWithDataDriven" time="1.830" classname="com.deltaX.QATCs.RegisterationFormDataDrivenTestNG"/>
  <testcase name="InvokeBrowser" time="3.211" classname="com.deltaX.QATCs.RegisterationFormDataDrivenTestNG">
    <failure type="java.lang.AssertionError" message="An exception occured...">
      <![CDATA[java.lang.AssertionError: An exception occured...
at org.testng.Assert.fail(Assert.java:96)
at com.deltaX.QATCs.BasicScenarios.InvokeBrowser(BasicScenarios.java:103)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:520)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- InvokeBrowser -->
  <testcase name="RegisterationWithDataDriven" time="2.752" classname="com.deltaX.QATCs.RegisterationFormDataDrivenTestNG"/>
  <testcase name="RegisterationWithDataDriven" time="0.000" classname="com.deltaX.QATCs.RegisterationFormDataDrivenTestNG">
    <skipped/>
  </testcase> <!-- RegisterationWithDataDriven -->
</testsuite> <!-- com.deltaX.QATCs.RegisterationFormDataDrivenTestNG -->
